package com.jingli.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-01-24T16:57:53.864+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.bee2c.com/DacOrderStateUpdateSrv/", name = "DacOrderStateUpdateSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DacOrderStateUpdateSrv {

    @WebMethod(action = "http://www.bee2c.com/DacOrderStateUpdateSrv/process")
    @WebResult(name = "DacOrderStateUpdateResponse", targetNamespace = "http://www.bee2c.com/DacOrderStateUpdateSrv/", partName = "parameters")
    public DacOrderStateUpdateResponse process(
        @WebParam(partName = "parameters", name = "DacOrderStateUpdateRequest", targetNamespace = "http://www.bee2c.com/DacOrderStateUpdateSrv/")
        DacOrderStateUpdateRequest parameters
    );
}
