package com.jingli.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-01-24T16:57:53.917+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "DacOrderStateUpdateSrvService", 
                  wsdlLocation = "http://127.0.0.1:8888/jinglitmc?wsdl",
                  targetNamespace = "http://www.bee2c.com/DacOrderStateUpdateSrv/") 
public class DacOrderStateUpdateSrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.bee2c.com/DacOrderStateUpdateSrv/", "DacOrderStateUpdateSrvService");
    public final static QName DacOrderStateUpdateSrvPort = new QName("http://www.bee2c.com/DacOrderStateUpdateSrv/", "DacOrderStateUpdateSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8888/jinglitmc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DacOrderStateUpdateSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8888/jinglitmc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DacOrderStateUpdateSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DacOrderStateUpdateSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DacOrderStateUpdateSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DacOrderStateUpdateSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DacOrderStateUpdateSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DacOrderStateUpdateSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DacOrderStateUpdateSrv
     */
    @WebEndpoint(name = "DacOrderStateUpdateSrvPort")
    public DacOrderStateUpdateSrv getDacOrderStateUpdateSrvPort() {
        return super.getPort(DacOrderStateUpdateSrvPort, DacOrderStateUpdateSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DacOrderStateUpdateSrv
     */
    @WebEndpoint(name = "DacOrderStateUpdateSrvPort")
    public DacOrderStateUpdateSrv getDacOrderStateUpdateSrvPort(WebServiceFeature... features) {
        return super.getPort(DacOrderStateUpdateSrvPort, DacOrderStateUpdateSrv.class, features);
    }

}
